import { M_PLUS_1 } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from './lib/registry';

const mplus1 = M_PLUS_1({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mplus1.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
